[phases.setup]
nixPkgs = ['php83', 'php83Packages.composer']

[phases.install]
cmds = ['composer install --optimize-autoloader --no-dev --no-scripts']

[phases.build]
cmds = ['npm install', 'npm run build']

[start]
cmd = 'php artisan config:cache && php artisan route:cache && php artisan serve --host=0.0.0.0 --port=$PORT'