[build]
builder = "nixpacks"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["php83", "php83Packages.composer", "nodejs_20"]

[build.nixpacksPlan.phases.install]
cmds = ["composer install --optimize-autoloader --no-dev", "npm install"]

[build.nixpacksPlan.phases.build]
cmds = ["npm run build"]